// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1czfsjR3PEoORg_ijAZJycfP_85_ONc8',
    appId: '1:217790338444:web:c7be96ade9ae0696c832a9',
    messagingSenderId: '217790338444',
    projectId: 'database-6ee9a',
    authDomain: 'database-6ee9a.firebaseapp.com',
    storageBucket: 'database-6ee9a.appspot.com',
    measurementId: 'G-FD568VG9K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPKpPtP3V0IFRhBQY0IyB58L0G-SHwaco',
    appId: '1:217790338444:android:18ab8924d7bb6c6ec832a9',
    messagingSenderId: '217790338444',
    projectId: 'database-6ee9a',
    storageBucket: 'database-6ee9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQEoOliVCavwErPd73KoufvIUpfblX8Os',
    appId: '1:217790338444:ios:76ef61307e298686c832a9',
    messagingSenderId: '217790338444',
    projectId: 'database-6ee9a',
    storageBucket: 'database-6ee9a.appspot.com',
    iosClientId: '217790338444-ksmm979toiqa683m81svchqtbksp5vcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQEoOliVCavwErPd73KoufvIUpfblX8Os',
    appId: '1:217790338444:ios:76ef61307e298686c832a9',
    messagingSenderId: '217790338444',
    projectId: 'database-6ee9a',
    storageBucket: 'database-6ee9a.appspot.com',
    iosClientId: '217790338444-ksmm979toiqa683m81svchqtbksp5vcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
